/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jnihelpertest_JNI */

#ifndef _Included_com_example_jnihelpertest_JNI
#define _Included_com_example_jnihelpertest_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jnihelpertest_JNI
 * Method:    Test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_jnihelpertest_JNI_Test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
